FROM    debian:11.11

RUN     apt  update && apt  upgrade \
        && apt  install mariadb-server -y

COPY    ./conf/mariadb.sh ./usr/local/bin/

RUN     sed -i 's/bind-address.*/bind-addres=0.0.0.0/' /etc/mysql/mariadb.conf.d/50-server.cnf

#EXPOSE  3306:3306

RUN     chmod +x ./usr/local/bin/mariadb.sh

CMD     [ "mariadb.sh" ]