FROM    debian:11.11

RUN     apt update && apt upgrade \
        && apt install php-fpm \
        php-mysql wget -y   

COPY    ./conf/wordpress.sh .

RUN     chmod +x wordpress.sh

#EXPOSE  9000:9000

CMD     ["./wordpress.sh"]

