FROM    debian:11.11

RUN     apt update && apt upgrade \
        && apt install nginx -y

RUN     mkdir -p etc/nginx/ssl/


RUN     apt update && apt upgrade \
        && apt install openssl -y \
        && openssl req -x509 -nodes \
        -out /etc/nginx/ssl/aelbouaa.42.fr.crt \
        -keyout etc/nginx/ssl/aelbouaa.42.fr.key \
        -subj "/C=MA/ST=RH/L=BG/O=UM6P/OU=1337/CN=aelbouaa.42.fr"

COPY    ./conf/nginx.conf  etc/nginx/conf.d/

RUN     chown -R www-data:www-data /var/www/html/

RUN     chown -R www-data:www-data /etc/nginx/ssl/

RUN     touch /var/www/html/index.php

CMD     ["nginx", "-g", "daemon off;"]